import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BootstrapClient from "@/lib/BootStrapClient";
import 'bootstrap/dist/css/bootstrap.min.css';
import Navb from "./components/navbar";
import { SearchProvider } from "./context/SearchContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <BootstrapClient/>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <SearchProvider>

        <Navb/>
        {children}
        </SearchProvider>
      </body>
    </html>
  );
}
